spring:
  application:
    name: 'fornecedor'
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/fornecedor?createDatabaseIfNotExist=true
  jpa:
    hibernate.ddl-auto: update
